const recipes = [
	{
		id: 0,
		date: "2025-10-13",
		name: "Lasagne",
		imgUrl: "img/lasang.jpg",
		alt: "Hjemmelaget lasagne på tallerken",
		rating: 4,
		comment: "Denne smakte godt",
		portionSize: 2,
		region: "Italia",
		description: "Deilig hjemmelaget Lasagne",
		ingredients: [
			{ ingredient: "Kjøttdeig", amount: 400, metric: "gram" },
			{ ingredient: "Løk", amount: 1, metric: "stk" },
			{ ingredient: "Salt", amount: 0.5, metric: "ss" },
		],
		recipeSteps: ["Gjør noe", "Gjør noe annet", "Gjør dette også", "Også dette"],
	},
	{
		id: 1,
		date: "2025-10-14",
		name: "Taco",
		imgUrl: "img/taco-1.jpg",
		alt: "Taco med ferskt tilbehør",
		rating: 3,
		comment: "Verdens beste fredagsmiddag!",
		portionSize: 4,
		region: "Mexico",
		description: "Klassisk norsk fredagstaco",
		ingredients: [
			{ ingredient: "Tacokjøttdeig", amount: 400, metric: "gram" },
			{ ingredient: "Tacolefser", amount: 8, metric: "stk" },
			{ ingredient: "Salsa", amount: 1, metric: "glass" },
		],
		recipeSteps: ["Stek kjøttdeig", "Bland krydder", "Server med tilbehør"],
	},
	{
		id: 2,
		date: "2025-10-16",
		name: "Kylling Tikka Masala",
		imgUrl: "img/tikkamashalla.jpg",
		alt: "Kylling Tikka Masala i en bolle",
		rating: 4.5,
		comment: "Lett å lage, men den hjemmelagde sausen krever litt jobb.",
		portionSize: 3,
		region: "India",
		description: "Kremet og smakfull indisk kyllingrett.",
		ingredients: [
			{ ingredient: "Kyllingfilet", amount: 600, metric: "gram" },
			{ ingredient: "Fløte", amount: 3, metric: "dl" },
			{ ingredient: "Tikka Masala saus", amount: 1, metric: "glass" },
			{ ingredient: "Ris", amount: 300, metric: "200" },
		],
		recipeSteps: ["Stek kylling", "Tilsett saus og fløte", "La det putre", "Server med ris"],
	},
];
