export const recipeModel = [
	{
		id: 0,
		date: "2025-10-13",
		name: "Lasagne",
		imgUrl: "assets/img/lasagne.jpg",
		alt: "Hjemmelaget lasagne på tallerken",
		rating: 4,
		comment: "Denne smakte godt",
		portionSize: 2,
		region: "Italia",
		description: "Deilig hjemmelaget Lasagne",
		ingredients: [
			{ ingredient: "Kjøttdeig", amount: 400, metric: "gram" },
			{ ingredient: "Løk", amount: 1, metric: "stk" },
			{ ingredient: "Salt", amount: 0.5, metric: "ss" },
		],
		recipeSteps: ["Gjør noe", "Gjør noe annet", "Gjør dette også", "Også dette"],
	},
	{
		id: 1,
		date: "2025-10-16",
		name: "Kylling Tikka Masala",
		imgUrl: "assets/img/tikka.jpg",
		alt: "Kylling Tikka Masala i en bolle",
		rating: 4.5,
		comment: "Lett å lage, men den hjemmelagde sausen krever litt jobb.",
		portionSize: 3,
		region: "India",
		description: "Kremet og smakfull indisk kyllingrett.",
		ingredients: [
			{ ingredient: "Kyllingfilet", amount: 600, metric: "gram" },
			{ ingredient: "Fløte", amount: 3, metric: "dl" },
			{ ingredient: "Tikka Masala saus", amount: 1, metric: "glass" },
			{ ingredient: "Ris", amount: 300, metric: "Gram" },
		],
		recipeSteps: ["Stek kylling", "Tilsett saus og fløte", "La det putre", "Server med ris"],
	},
	{
		id: 2,
		date: "2025-10-14",
		name: "Taco",
		imgUrl: "assets/img/taco.jpg",
		alt: "Taco med ferskt tilbehør",
		rating: 3,
		comment: "Verdens beste fredagsmiddag!",
		portionSize: 4,
		region: "Mexico",
		description: "Klassisk norsk fredagstaco",
		ingredients: [
			{ ingredient: "Tacokjøttdeig", amount: 400, metric: "gram" },
			{ ingredient: "Tacolefser", amount: 8, metric: "stk" },
			{ ingredient: "Salsa", amount: 1, metric: "glass" },
		],
		recipeSteps: ["Stek kjøttdeig", "Bland krydder", "Server med tilbehør"],
	},
	{
		id: 3,
		date: "2025-10-17",
		name: "Spaghetti Carbonara",
		imgUrl: "assets/img/carbonara.jpg",
		alt: "Spaghetti Carbonara med egg og parmesan",
		rating: 5,
		comment: "Enkel, rask og utrolig smakfull! Bruk ekte Guanciale for best resultat.",
		portionSize: 2,
		region: "Italia",
		description: "Klassisk italiensk pasta med egg, Pecorino Romano, guanciale/pancetta og sort pepper.",
		ingredients: [
			{ ingredient: "Spaghetti", amount: 200, metric: "gram" },
			{ ingredient: "Egg", amount: 2, metric: "stk" },
			{ ingredient: "Pancetta/Guanciale", amount: 100, metric: "gram" },
			{ ingredient: "Pecorino Romano", amount: 50, metric: "gram" },
		],
		recipeSteps: ["Kok pasta", "Stek pancetta", "Bland egg/ost", "Bland alt raskt"],
	},
	{
		id: 4,
		date: "2025-10-18",
		name: "Tomatsuppe",
		imgUrl: "assets/img/tomatsuppe.jpg",
		alt: "Hjemmelaget tomatsuppe i en bolle med egg",
		rating: 4,
		comment: "Varmende og god på en kald dag. Perfekt med et kokt egg i.",
		portionSize: 4,
		region: "Norge",
		description: "Lettvint og næringsrik tomatsuppe, passer perfekt med makaroni og egg.",
		ingredients: [
			{ ingredient: "Hermetiske tomater", amount: 2, metric: "boks" },
			{ ingredient: "Vann/buljong", amount: 5, metric: "dl" },
			{ ingredient: "Løk", amount: 0.5, metric: "stk" },
			{ ingredient: "Egg", amount: 4, metric: "stk" },
		],
		recipeSteps: ["Fres løk", "Tilsett tomater og vann", "Kok opp", "Server med egg"],
	},
	{
		id: 5,
		date: "2025-10-19",
		name: "Laksefilet med grønnsaker",
		imgUrl: "assets/img/laks-gronnsaker-ovn.jpg",
		alt: "Stekt laksefilet med dampede grønnsaker",
		rating: 4.5,
		comment: "Veldig sunt og enkelt. Bruk gjerne sitron og dill.",
		portionSize: 2,
		region: "Norge",
		description: "Sunn og enkel middag med laks og friske grønnsaker.",
		ingredients: [
			{ ingredient: "Laksefilet", amount: 300, metric: "gram" },
			{ ingredient: "Brokkoli", amount: 1, metric: "hode" },
			{ ingredient: "Gulrot", amount: 2, metric: "stk" },
			{ ingredient: "Smør", amount: 20, metric: "gram" },
		],
		recipeSteps: ["Stek laks", "Damp grønnsaker", "Krydre", "Server"],
	},
	{
		id: 6,
		date: "2025-10-20",
		name: "Biff Stroganoff",
		imgUrl: "assets/img/stroganoff.jpg",
		alt: "Biff Stroganoff med ris og rømme",
		rating: 4,
		comment: "Klassiker fra Russland. Sausen er høydepunktet!",
		portionSize: 3,
		region: "Russland",
		description: "Russisk klassiker med strimler av oksekjøtt i en kremet soppsaus.",
		ingredients: [
			{ ingredient: "Indrefilet av storfe", amount: 400, metric: "gram" },
			{ ingredient: "Sjampinjong", amount: 200, metric: "gram" },
			{ ingredient: "Creme Fraiche", amount: 3, metric: "dl" },
			{ ingredient: "Løk", amount: 1, metric: "stk" },
		],
		recipeSteps: ["Stek biff", "Fres løk/sopp", "Lag saus", "Server med ris/potetmos"],
	},
	{
		id: 7,
		date: "2025-10-21",
		name: "Pannekaker",
		imgUrl: "assets/img/pannekaker.jpg",
		alt: "Stack av pannekaker med bær",
		rating: 5,
		comment: "Funker til alle måltider. Perfekt med syltetøy og sukker.",
		portionSize: 4,
		region: "Global",
		description: "Tradisjonelle tynne pannekaker.",
		ingredients: [
			{ ingredient: "Mel", amount: 300, metric: "gram" },
			{ ingredient: "Melk", amount: 5, metric: "dl" },
			{ ingredient: "Egg", amount: 3, metric: "stk" },
			{ ingredient: "Smør", amount: 30, metric: "gram" },
		],
		recipeSteps: ["Bland røre", "Stek i panne", "Vend", "Server"],
	},
	{
		id: 8,
		date: "2025-10-22",
		name: "Shepherd's Pie",
		imgUrl: "assets/img/shepherds_pie.jpg",
		alt: "Shepherd's Pie med potetmos-topp",
		rating: 3.5,
		comment: "Mye jobb, men veldig mettende og god tradisjonsmat.",
		portionSize: 4,
		region: "Storbritannia",
		description: "Engelsk/Irsk kjøttdeigrett toppet med potetmos.",
		ingredients: [
			{ ingredient: "Kjøttdeig (lam)", amount: 500, metric: "gram" },
			{ ingredient: "Poteter", amount: 800, metric: "gram" },
			{ ingredient: "Gulrot", amount: 2, metric: "stk" },
			{ ingredient: "Erter", amount: 100, metric: "gram" },
		],
		recipeSteps: ["Lag kjøttfyll", "Lag potetmos", "Monter i form", "Stek"],
	},
	{
		id: 9,
		date: "2025-10-23",
		name: "Pho Bo",
		imgUrl: "assets/img/pho-bo.jpg",
		alt: "Vietnamesisk Pho Bo nudelsuppe",
		rating: 4.5,
		comment: "Buljongen krever lang koketid, men det er verdt det.",
		portionSize: 2,
		region: "Vietnam",
		description: "Klassisk vietnamesisk biff-nudelsuppe.",
		ingredients: [
			{ ingredient: "Oksekjøtt", amount: 200, metric: "gram" },
			{ ingredient: "Risenudler", amount: 150, metric: "gram" },
			{ ingredient: "Buljong (hjemmelaget)", amount: 10, metric: "dl" },
			{ ingredient: "Bønnespirer", amount: 50, metric: "gram" },
		],
		recipeSteps: ["Kok buljong", "Forbered garnityr", "Kok nudler", "Server"],
	},
	{
		id: 10,
		date: "2025-10-24",
		name: "Paella Valenciana",
		imgUrl: "assets/img/paella.jpg",
		alt: "Paella med sjømat, kylling og ris",
		rating: 4,
		comment: "Smakfull, men litt vanskelig å få til den perfekte 'socarrat' (skorpen).",
		portionSize: 4,
		region: "Spania",
		description: "Spansk risrett med sjømat, kylling og safran.",
		ingredients: [
			{ ingredient: "Paella ris", amount: 300, metric: "gram" },
			{ ingredient: "Kylling", amount: 300, metric: "gram" },
			{ ingredient: "Sjømatmiks", amount: 200, metric: "gram" },
			{ ingredient: "Safran", amount: 0.5, metric: "ts" },
		],
		recipeSteps: ["Fres kjøtt/sjømat", "Tilsett ris/buljong", "Kok sakte", "La hvile"],
	},
	{
		id: 11,
		date: "2025-10-25",
		name: "Pizza Margherita (hjemmelaget)",
		imgUrl: "assets/img/pizza-margerita.jpg",
		alt: "Hjemmelaget Pizza Margherita",
		rating: 5,
		comment: "Ingenting slår hjemmelaget pizza. Bruk god mozzarella!",
		portionSize: 2,
		region: "Italia",
		description: "Enkel og klassisk italiensk pizza med tomat, mozzarella og basilikum.",
		ingredients: [
			{ ingredient: "Pizzadeig", amount: 300, metric: "gram" },
			{ ingredient: "Tomatsaus", amount: 100, metric: "gram" },
			{ ingredient: "Mozzarella", amount: 150, metric: "gram" },
			{ ingredient: "Basilikum", amount: 1, metric: "kvist" },
		],
		recipeSteps: ["Lag/kjevle deig", "Påfør saus/ost", "Stek i varm ovn", "Pynt med basilikum"],
	},
	{
		id: 12,
		date: "2025-10-26",
		name: "Gulasj",
		imgUrl: "assets/img/gulasj.jpg",
		alt: "Ungarsk gulasj servert i en bolle",
		rating: 4,
		comment: "Lang koketid, men en deilig gryte på høsten.",
		portionSize: 4,
		region: "Ungarn",
		description: "Ungarsk kjøttgryte med paprika og poteter.",
		ingredients: [
			{ ingredient: "Oksekjøtt (grytekjøtt)", amount: 600, metric: "gram" },
			{ ingredient: "Løk", amount: 2, metric: "stk" },
			{ ingredient: "Paprikapulver", amount: 3, metric: "ss" },
			{ ingredient: "Poteter", amount: 500, metric: "gram" },
		],
		recipeSteps: ["Brun kjøtt", "Fres løk/paprika", "Tilsett buljong/kok lenge", "Tilsett poteter"],
	},
];
