export const recipeModel = [
    {
        id: 0,
        date: "2025-10-13",
        name: "Lasagne",
        imgUrl: "assets/img/lasagne.jpg",
        alt: "Hjemmelaget lasagne på tallerken",
        rating: 4,
        comment: "Denne smakte godt",
        portionSize: 2,
        region: "Italia",
        description: "Deilig hjemmelaget Lasagne",
        ingredients: [
            { ingredient: "Kjøttdeig", amount: 400, metric: "gram" },
            { ingredient: "Løk", amount: 1, metric: "stk" },
            { ingredient: "Salt", amount: 0.5, metric: "ss" },
        ],
        recipeSteps: ["Gjør noe", "Gjør noe annet", "Gjør dette også", "Også dette"],
    },
    {
        id: 1,
        date: "2025-10-16",
        name: "Kylling Tikka Masala",
        imgUrl: "assets/img/tikka.jpg",
        alt: "Kylling Tikka Masala i en bolle",
        rating: 4.5,
        comment: "Lett å lage, men den hjemmelagde sausen krever litt jobb.",
        portionSize: 3,
        region: "India",
        description: "Kremet og smakfull indisk kyllingrett.",
        ingredients: [
            { ingredient: "Kyllingfilet", amount: 600, metric: "gram" },
            { ingredient: "Fløte", amount: 3, metric: "dl" },
            { ingredient: "Tikka Masala saus", amount: 1, metric: "glass" },
            { ingredient: "Ris", amount: 300, metric: "Gram" },
        ],
        recipeSteps: ["Stek kylling", "Tilsett saus og fløte", "La det putre", "Server med ris"],
    },
    {
        id: 2,
        date: "2025-10-14",
        name: "Taco",
        imgUrl: "assets/img/taco.jpg",
        alt: "Taco med ferskt tilbehør",
        rating: 3,
        comment: "Verdens beste fredagsmiddag!",
        portionSize: 4,
        region: "Mexico",
        description: "Klassisk norsk fredagstaco",
        ingredients: [
            { ingredient: "Tacokjøttdeig", amount: 400, metric: "gram" },
            { ingredient: "Tacolefser", amount: 8, metric: "stk" },
            { ingredient: "Salsa", amount: 1, metric: "glass" },
        ],
        recipeSteps: ["Stek kjøttdeig", "Bland krydder", "Server med tilbehør"],
    },
    {
        id: 3,
        date: "2025-10-17",
        name: "Spaghetti Carbonara",
        imgUrl: "assets/img/carbonara.jpg",
        alt: "Spaghetti Carbonara med egg og parmesan",
        rating: 5,
        comment: "Enkel, rask og utrolig smakfull! Bruk ekte Guanciale for best resultat.",
        portionSize: 2,
        region: "Italia",
        description:
            "Klassisk italiensk pasta med egg, Pecorino Romano, guanciale/pancetta og sort pepper.",
        ingredients: [
            { ingredient: "Spaghetti", amount: 200, metric: "gram" },
            { ingredient: "Egg", amount: 2, metric: "stk" },
            { ingredient: "Pancetta/Guanciale", amount: 100, metric: "gram" },
            { ingredient: "Pecorino Romano", amount: 50, metric: "gram" },
        ],
        recipeSteps: ["Kok pasta", "Stek pancetta", "Bland egg/ost", "Bland alt raskt"],
    },
    {
        id: 4,
        date: "2025-10-18",
        name: "Tomatsuppe",
        imgUrl: "assets/img/tomatsuppe.jpg",
        alt: "Hjemmelaget tomatsuppe i en bolle med egg",
        rating: 4,
        comment: "Varmende og god på en kald dag. Perfekt med et kokt egg i.",
        portionSize: 4,
        region: "Norge",
        description: "Lettvint og næringsrik tomatsuppe, passer perfekt med makaroni og egg.",
        ingredients: [
            { ingredient: "Hermetiske tomater", amount: 2, metric: "boks" },
            { ingredient: "Vann/buljong", amount: 5, metric: "dl" },
            { ingredient: "Løk", amount: 0.5, metric: "stk" },
            { ingredient: "Egg", amount: 4, metric: "stk" },
        ],
        recipeSteps: ["Fres løk", "Tilsett tomater og vann", "Kok opp", "Server med egg"],
    },
    {
        id: 5,
        date: "2025-10-19",
        name: "Laksefilet med grønnsaker",
        imgUrl: "assets/img/laks-gronnsaker-ovn.jpg",
        alt: "Stekt laksefilet med dampede grønnsaker",
        rating: 4.5,
        comment: "Veldig sunt og enkelt. Bruk gjerne sitron og dill.",
        portionSize: 2,
        region: "Norge",
        description: "Sunn og enkel middag med laks og friske grønnsaker.",
        ingredients: [
            { ingredient: "Laksefilet", amount: 300, metric: "gram" },
            { ingredient: "Brokkoli", amount: 1, metric: "hode" },
            { ingredient: "Gulrot", amount: 2, metric: "stk" },
            { ingredient: "Smør", amount: 20, metric: "gram" },
        ],
        recipeSteps: ["Stek laks", "Damp grønnsaker", "Krydre", "Server"],
    },
    {
        id: 6,
        date: "2025-10-20",
        name: "Biff Stroganoff",
        imgUrl: "assets/img/stroganoff.jpg",
        alt: "Biff Stroganoff med ris og rømme",
        rating: 4,
        comment: "Klassiker fra Russland. Sausen er høydepunktet!",
        portionSize: 3,
        region: "Russland",
        description: "Russisk klassiker med strimler av oksekjøtt i en kremet soppsaus.",
        ingredients: [
            { ingredient: "Indrefilet av storfe", amount: 400, metric: "gram" },
            { ingredient: "Sjampinjong", amount: 200, metric: "gram" },
            { ingredient: "Creme Fraiche", amount: 3, metric: "dl" },
            { ingredient: "Løk", amount: 1, metric: "stk" },
        ],
        recipeSteps: ["Stek biff", "Fres løk/sopp", "Lag saus", "Server med ris/potetmos"],
    },
    {
        id: 7,
        date: "2025-10-21",
        name: "Pannekaker",
        imgUrl: "assets/img/pannekaker.jpg",
        alt: "Stack av pannekaker med bær",
        rating: 5,
        comment: "Funker til alle måltider. Perfekt med syltetøy og sukker.",
        portionSize: 4,
        region: "Global",
        description: "Tradisjonelle tynne pannekaker.",
        ingredients: [
            { ingredient: "Mel", amount: 300, metric: "gram" },
            { ingredient: "Melk", amount: 5, metric: "dl" },
            { ingredient: "Egg", amount: 3, metric: "stk" },
            { ingredient: "Smør", amount: 30, metric: "gram" },
        ],
        recipeSteps: ["Bland røre", "Stek i panne", "Vend", "Server"],
    },
    {
        id: 8,
        date: "2025-10-22",
        name: "Shepherd's Pie",
        imgUrl: "assets/img/shepherds_pie.jpg",
        alt: "Shepherd's Pie med potetmos-topp",
        rating: 3.5,
        comment: "Mye jobb, men veldig mettende og god tradisjonsmat.",
        portionSize: 4,
        region: "Storbritannia",
        description: "Engelsk/Irsk kjøttdeigrett toppet med potetmos.",
        ingredients: [
            { ingredient: "Kjøttdeig (lam)", amount: 500, metric: "gram" },
            { ingredient: "Poteter", amount: 800, metric: "gram" },
            { ingredient: "Gulrot", amount: 2, metric: "stk" },
            { ingredient: "Erter", amount: 100, metric: "gram" },
        ],
        recipeSteps: ["Lag kjøttfyll", "Lag potetmos", "Monter i form", "Stek"],
    },
    {
        id: 9,
        date: "2025-10-23",
        name: "Pho Bo",
        imgUrl: "assets/img/pho-bo.jpg",
        alt: "Vietnamesisk Pho Bo nudelsuppe",
        rating: 4.5,
        comment: "Buljongen krever lang koketid, men det er verdt det.",
        portionSize: 2,
        region: "Vietnam",
        description: "Klassisk vietnamesisk biff-nudelsuppe.",
        ingredients: [
            { ingredient: "Oksekjøtt", amount: 200, metric: "gram" },
            { ingredient: "Risenudler", amount: 150, metric: "gram" },
            { ingredient: "Buljong (hjemmelaget)", amount: 10, metric: "dl" },
            { ingredient: "Bønnespirer", amount: 50, metric: "gram" },
        ],
        recipeSteps: ["Kok buljong", "Forbered garnityr", "Kok nudler", "Server"],
    },
    {
        id: 10,
        date: "2025-10-24",
        name: "Paella Valenciana",
        imgUrl: "assets/img/paella.jpg",
        alt: "Paella med sjømat, kylling og ris",
        rating: 4,
        comment: "Smakfull, men litt vanskelig å få til den perfekte 'socarrat' (skorpen).",
        portionSize: 4,
        region: "Spania",
        description: "Spansk risrett med sjømat, kylling og safran.",
        ingredients: [
            { ingredient: "Paella ris", amount: 300, metric: "gram" },
            { ingredient: "Kylling", amount: 300, metric: "gram" },
            { ingredient: "Sjømatmiks", amount: 200, metric: "gram" },
            { ingredient: "Safran", amount: 0.5, metric: "ts" },
        ],
        recipeSteps: ["Fres kjøtt/sjømat", "Tilsett ris/buljong", "Kok sakte", "La hvile"],
    },
    {
        id: 11,
        date: "2025-10-25",
        name: "Pizza Margherita (hjemmelaget)",
        imgUrl: "assets/img/pizza-margerita.jpg",
        alt: "Hjemmelaget Pizza Margherita",
        rating: 5,
        comment: "Ingenting slår hjemmelaget pizza. Bruk god mozzarella!",
        portionSize: 2,
        region: "Italia",
        description: "Enkel og klassisk italiensk pizza med tomat, mozzarella og basilikum.",
        ingredients: [
            { ingredient: "Pizzadeig", amount: 300, metric: "gram" },
            { ingredient: "Tomatsaus", amount: 100, metric: "gram" },
            { ingredient: "Mozzarella", amount: 150, metric: "gram" },
            { ingredient: "Basilikum", amount: 1, metric: "kvist" },
        ],
        recipeSteps: ["Lag/kjevle deig", "Påfør saus/ost", "Stek i varm ovn", "Pynt med basilikum"],
    },
    {
        id: 12,
        date: "2025-10-26",
        name: "Gulasj",
        imgUrl: "assets/img/gulasj.jpg",
        alt: "Ungarsk gulasj servert i en bolle",
        rating: 4,
        comment: "Lang koketid, men en deilig gryte på høsten.",
        portionSize: 4,
        region: "Ungarn",
        description: "Ungarsk kjøttgryte med paprika og poteter.",
        ingredients: [
            { ingredient: "Oksekjøtt (grytekjøtt)", amount: 600, metric: "gram" },
            { ingredient: "Løk", amount: 2, metric: "stk" },
            { ingredient: "Paprikapulver", amount: 3, metric: "ss" },
            { ingredient: "Poteter", amount: 500, metric: "gram" },
        ],
        recipeSteps: [
            "Brun kjøtt",
            "Fres løk/paprika",
            "Tilsett buljong/kok lenge",
            "Tilsett poteter",
        ],
    },
    {
        id: 12,
        date: "2025-10-26",
        name: "Dhal med ovnsbakt flaskegresskar",
        imgUrl: "assets/img/dhal.jpg",
        alt: "Dhal med ovnsbakt flaskegresskar og tilbehør",
        rating: 4,
        comment: "Deilig og næringsrik rett med indiske smaker.",
        portionSize: 4,
        region: "India",
        description:
            "Kremet dhal med ovnsbakt flaskegresskar, servert med mangochutney, yoghurt og nanbrød.",
        ingredients: [
            { ingredient: "Flaskegresskar", amount: 1, metric: "stk" },
            { ingredient: "Kjerneblanding", amount: 1, metric: "pakke" },
            { ingredient: "Gul løk", amount: 1, metric: "stk" },
            { ingredient: "Hvitløksfedd", amount: 1, metric: "stk" },
            { ingredient: "Norsk eple", amount: 1, metric: "stk" },
            { ingredient: "Tikka masala-paste", amount: 0.5, metric: "glass" },
            { ingredient: "Grønne linser", amount: 1, metric: "pakke" },
            { ingredient: "Kokoskre­m", amount: 1, metric: "pakke" },
            { ingredient: "Lime", amount: 1, metric: "stk" },
            { ingredient: "Vann", amount: 2, metric: "dl" },
            { ingredient: "Nanbrød", amount: 1, metric: "pakke" },
            { ingredient: "Mangochutney", amount: 1, metric: "glass" },
            { ingredient: "Yoghurt naturell", amount: 0.5, metric: "pakke" },
            { ingredient: "Olje", amount: null, metric: "litt" },
            { ingredient: "Salt", amount: null, metric: "etter smak" },
            { ingredient: "Pepper", amount: null, metric: "etter smak" },
        ],
        recipeSteps: [
            "Varm opp stekeovnen til 220 grader varmluft.",
            "Ovnsbakt flaskegresskar: Skyll gresskaret godt. Kutt det i to på langs, og skrap ut frøene med en skje. Kutt deretter gresskaret i skiver. Fordel skivene utover et stekebrett med bakepapir, og vend inn litt olje, salt og pepper. Stek gresskarskivene i ovnen i omtrent 20 minutter. Ta ut stekebrettet etter 15 minutter, og strø over kjerneblandingen. Stek det hele videre i 5 minutter til frøene er gyllene.",
            "Dhal: Skrell løken og hvitløken, og skyll eplet. Finhakk hvitløken, og kutt løken og eplet i terninger. Sil laken av linsene.",
            "Dhal, fortsettelse: Varm opp en kjele til middels høy varme, og ha i litt olje. Ha i ønsket mengde tikka masala-paste, og la det surre i et lite minutt. Tilsett deretter hvitløken, løken og eplet, og la det steke videre i omtrent 3 minutter, eller til løken er gyllen. Ha i linsene, kokoskre­men og 2 dl vann, og gi det hele et oppkok. Skru ned varmen, og la gryten småkoke i 10–12 minutter. Rør inn mellom. Smak til med salt, pepper og saften fra limen før servering.",
            "Nanbrød: Varm nanbrødene i ovnen i 2–3 minutter.",
            "Tilbehør: Server mangochutney, yoghurt og nanbrød til retten.",
        ],
    },
    {
        id: 13,
        date: "2025-10-27",
        name: "Squash- og fetakaker med thailandsk agurksalat",
        imgUrl: "assets/img/squash-og-fetakaker.jpg",
        alt: "Squash- og fetakaker med thailandsk agurksalat og tilbehør",
        rating: 4.5,
        comment: "Frisk og smakfull rett med asiatiske toner.",
        portionSize: 4,
        region: "Thailand",
        description:
            "Sprø squash- og fetakaker servert med thailandsk agurksalat, sweet chili-saus og jasminris.",
        ingredients: [
            { ingredient: "Squash", amount: 1, metric: "stk" },
            { ingredient: "Koriander", amount: 0.5, metric: "bunt" },
            { ingredient: "Fetaost", amount: 50, metric: "g" },
            { ingredient: "Egg", amount: 2, metric: "stk" },
            { ingredient: "Finkuttet ingefær, hvitløk og chili", amount: 0.5, metric: "pakke" },
            { ingredient: "Hvetemel", amount: 1, metric: "dl" },
            { ingredient: "Agurk", amount: 0.5, metric: "stk" },
            { ingredient: "Rødløk", amount: 0.5, metric: "stk" },
            { ingredient: "Eplesider-/hvitvinseddik", amount: 0.25, metric: "dl" },
            { ingredient: "Sukker", amount: 1, metric: "ss" },
            { ingredient: "Salt", amount: 0.5, metric: "ts" },
            { ingredient: "Jasminris", amount: 135, metric: "g" },
            { ingredient: "Lime", amount: 1, metric: "stk" },
            { ingredient: "Sweet chili-saus", amount: 1, metric: "pakke" },
            { ingredient: "Hakkede peanøtter", amount: 1, metric: "pakke" },
            { ingredient: "Olje", amount: null, metric: "litt" },
        ],
        recipeSteps: [
            "Squash- og fetakaker: Riv squashen på den grove siden av et rivjern. Ha den revne squashen i et dørslag, og strø over litt salt. La squashen stå i et par minutter før du klemmer ut væsken med hendene. Skyll og finhakk korianderstilkene, spar bladene til topping. Smuldre fetaosten.",
            "Thailandsk agurksalat: Skyll og kutt agurken i to, og så i skiver på skrå. Skrell og finhakk rødløken. Rør sammen ¼ dl eddik, 1 ss sukker og ½ ts salt i en skål, til sukkeret er oppløst. Vend inn agurken, rødløken og 1 ts av ingefærblandingen i dressingen, og sett salaten i kjøleskapet.",
            "Jasminris: Tilbered risen som anvist på pakken.",
            "Squash- og fetakaker, fortsettelse: Bland squashen med eggene, korianderstilkene, fetaosten, 1 dl hvetemel, 1–2 ts av ingefærblandingen og litt salt i en skål. Varm opp en stekepanne til middels høy varme, og ha i litt olje. Stek små, flate kaker av squashblandingen, i 4–5 minutter på hver side. Legg squashkakene over på en tallerken, og dekk dem med et kjøkkenhåndkle slik at de holder seg varme frem til servering.",
            "Tilbehør: Kutt limen i båter. Ha limebåtene, sweet chili-sausen, korianderbladene og peanøttene i hver sin skål til servering.",
        ],
    },
    {
        id: 14,
        date: "2025-10-28",
        name: "Mild tofu korma med paprika, spinat og basmatiris",
        imgUrl: "assets/img/tofu-korma.jpg",
        alt: "Mild tofu korma med paprika, spinat og basmatiris",
        rating: 4,
        comment: "Kremet og mild indisk-inspirert rett med tofu.",
        portionSize: 2,
        region: "India",
        description: "Mild tofu korma servert med paprika, spinat og basmatiris.",
        ingredients: [
            { ingredient: "Basmatiris", amount: 135, metric: "g" },
            { ingredient: "Gul løk", amount: 0.5, metric: "stk" },
            { ingredient: "Rød paprika", amount: 1, metric: "stk" },
            { ingredient: "Spinat", amount: 50, metric: "g" },
            { ingredient: "Tofu med chili & sitrongress", amount: 1, metric: "pakke" },
            { ingredient: "Kormapaste", amount: 0.25, metric: "glass" },
            { ingredient: "Kokoskrem", amount: 1, metric: "pakke" },
            { ingredient: "Finkuttet ingefær, hvitløk og chili", amount: 0.25, metric: "pakke" },
            { ingredient: "Vann", amount: 1, metric: "dl" },
            { ingredient: "Smør", amount: 0.5, metric: "ss" },
            { ingredient: "Olje", amount: null, metric: "litt" },
            { ingredient: "Salt", amount: null, metric: "etter smak" },
            { ingredient: "Pepper", amount: null, metric: "etter smak" },
        ],
        recipeSteps: [
            "Ris: Tilbered risen som anvist på pakken.",
            "Tofu korma, forberedelse: Skrell og grovhakk løken. Skyll, rens og kutt paprikaen i grove terninger. Skyll spinaten, og kutt tofuen i terninger.",
            "Tofu korma, fortsettelse: Varm opp en gryte til middels høy varme, og ha i litt olje. Stek løken i 3-4 minutter, til løken er blank. Ha i kormapasten og stek det hele videre i 2-3 minutter. Tilsett kokoskremen og 1 dl vann, og gi det hele et oppkok. La sausen småkoke på middels lav varme i omtrent 10 minutter. Ha i ½ ss smør, og kjør sausen jevn med en stavmikser. Vend inn spinaten, og smak til med salt. La kormaen stå på lav varme til resten av retten er klar.",
            "Tofu korma, fortsettelse: Varm opp en stekepanne til middels høy varme, og ha i ingefærblandingen. Stek tofuen og paprikaen i 2-3 minutter, til tofuen har fått en stekeskorpe. Krydre med salt og pepper, og topp kormaen med paprikaen og tofuen ved servering.",
            "God middag!",
        ],
    },
];
